run:
  timeout: 40s
  tests: true

linters-settings:
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 9
  gocognit:
    min-complexity: 10
  wsl:
    allow-assign-and-call: true
    allow-cuddle-declarations: true
    force-err-cuddling: true

linters:
  disable-all: true
  enable:
    - deadcode
    - revive
    - gosec
    - govet
    - nakedret
    - dupl
    - varcheck
    - typecheck
    # Disabled due to go1.18
    # - gosimple
    # - staticcheck
    # - unused
    # - structcheck

issues:
  exclude-rules:
    # Exclude some gosec messages
    - linters:
        - gosec
      text: "[G104, G404]"
  exclude-use-default: false