service: global-services
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  vpc: ${file(.env.global.yml):vpc}

  iam:
    role:
      statements: 
        - Effect: 'Allow'
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dispatch-globally:
    handler: bin/dispatch-globally
    environment: ${file(.env.dispatch-globally.yml)}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

  dispatch-globally-canary:
    handler: bin/dispatch-globally
    environment: ${file(.env.dispatch-globally.canary.yml)}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: false

  run-application-checks:
    handler: bin/run-application-checks
    environment: ${file(.env.run-application-checks.yml)}
    memorySize: 768
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true

  run-application-checks-canary:
    handler: bin/run-application-checks
    environment: ${file(.env.run-application-checks.canary.yml)}
    memorySize: 768
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(4 minutes)
          enabled: false

  perform-application-check:
    handler: bin/perform-application-check
    environment: ${file(.env.perform-application-check.yml)}
    memorySize: 256
    timeout: 360

  perform-application-check-canary:
    handler: bin/perform-application-check
    environment: ${file(.env.perform-application-check.yml)}
    memorySize: 256
    timeout: 360
    
  flush-cache:
    handler: bin/flush-cache
    environment: ${file(.env.flush-cache.yml)}
    memorySize: 128
    timeout: 20
