service: global-dispatcher
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dispatch-globally:
    handler: bin/dispatch-globally
    environment: ${file(.env.yml):environment}
    vpc: ${file(.env.yml):vpc}
    memorySize: 512
    timeout: 300
    maximumRetryAttempts: 2

    events:
      - schedule:
          rate: rate(6 minutes)
          enabled: false
