service: global-services
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  vpc: ${file(.env.global.yml):vpc}

  iam:
    role:
      statements: 
        - Effect: 'Allow'
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"
        # Enable this when creating a lambda inside a VPC
        # - Effect: Allow
        #   Action:
        #     - ec2:DescribeNetworkInterfaces
        #     - ec2:CreateNetworkInterface
        #     - ec2:DeleteNetworkInterface
        #     - ec2:DescribeInstances
        #     - ec2:AttachNetworkInterface
        #   Resource:
        #     - "*"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dispatch-globally:
    handler: bin/dispatch
    environment: ${file(.env.dispatch-globally.yml)}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

  dispatch-globally-canary:
    handler: bin/dispatch
    environment: ${file(.env.dispatch-globally.canary.yml)}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: false

  run-application-checks:
    handler: bin/run-application-checks
    environment: ${file(.env.run-application-checks.yml)}
    memorySize: 768
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true

  run-application-checks-canary:
    handler: bin/run-application-checks
    environment: ${file(.env.run-application-checks.canary.yml)}
    memorySize: 768
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(4 minutes)
          enabled: false

  perform-application-check:
    handler: bin/perform-application-check
    environment: ${file(.env.perform-application-check.yml)}
    memorySize: 256
    timeout: 60

  perform-application-check-canary:
    handler: bin/perform-application-check
    environment: ${file(.env.perform-application-check.canary.yml)}
    memorySize: 256
    timeout: 60

  snap-cherry-picker-data:
    handler: bin/snap-data
    environment: ${file(.env.snap-cherry-picker-data.yml)}
    memorySize: 1256
    timeout: 360
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
  
  snap-cherry-picker-data-node-runners:
    handler: bin/snap-data
    environment: ${file(.env.snap-cherry-picker-data.node-runners.yml)}
    memorySize: 1256
    timeout: 600
    maximumRetryAttempts: 2
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true

  snap-cherry-picker-data-canary:
    handler: bin/snap-data
    environment: ${file(.env.snap-cherry-picker-data.canary.yml)}
    memorySize: 1256
    timeout: 360

  flush-cache:
    handler: bin/flush
    environment: ${file(.env.flush-cache.yml)}
    memorySize: 128
    timeout: 20
