service: global-dispatcher
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  memorySize: 512
  timeout: 180

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dispatch-globally:
    handler: bin/dispatch-globally
    environment: ${file(.env.json):environment}
    vpc: ${file(.env.json):vpc}

    events:
      - schedule:
          rate: rate(6 minutes)
          enabled: true
