service: global-services
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  vpc: ${file(.env.global.yml):vpc}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dispatch-globally:
    handler: bin/dispatch-globally
    environment: ${file(.env.dispatch-globally.yml)}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2

    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

  run-application-checks:
    handler: bin/run-application-checks
    environment: ${file(.env.run-application-checks.yml)}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2
  
  flush-cache:
    handler: bin/flush-cache
    environment: ${file(.env.flush-cache.yml)}
    memorySize: 128
    timeout: 20
