service: global-dispatcher
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dispatch-globally:
    handler: bin/dispatch-globally
    environment: ${file(.env.dispatch-globally.yml):environment}
    vpc: ${file(.env.dispatch-globally.yml):vpc}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2

    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

  run-application-checks:
    handler: bin/run-application-checks
    environment: ${file(.env.run-application-checks.yml):environment}
    vpc: ${file(.env.run-application-checks.yml):vpc}
    memorySize: 256
    timeout: 360
    maximumRetryAttempts: 2